name: CloudCamp Demo

on:

  push:
    branches:
      - main

jobs:
  
  container-demo:
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-nanoserver
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check Java version
        run: java --version

  springboot-build:
    runs-on: ubuntu-latest
    outputs: ${{ steps.build.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build code
        run: |
          ./gradlew build
          echo "result=OK" >> $GITHUB_OUTPUTS

  springboot-container:
    runs-on: ubuntu-latest
    needs: springboot-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build container
        run: |
          ./gradlew build
          echo "result=OK" >> $GITHUB_OUTPUTS

