name: CloudCamp Demo

on:

  push:
    branches:
      - master

jobs:
  
  check-java-version:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check Java version
        run: java --version
